NOTES = {
    'SILENCE': 0,
    'A#3': 233,
    'A3': 220,
    'C#4': 277,
    'C2': 65,
    'C3': 131,
    'C4': 262,
    'D#2': 78,
    'D#3': 156,
    'D2': 73,
    'D3': 147,
    'D4': 294,
    'F1': 44,
    'F2': 87,
    'G1': 49,
    'G3': 196,
    'G4': 392,
}
TEMPO = 370
SUBDIV = 320
PIECE = [
    (NOTES['SILENCE'], TEMPO * 480 // SUBDIV),
    (NOTES['G3'], TEMPO * 240 // SUBDIV),
    (NOTES['A#3'], TEMPO * 192 // SUBDIV),
    (NOTES['C4'], TEMPO * 414 // SUBDIV),
    (NOTES['SILENCE'], TEMPO * 22 // SUBDIV),
    (NOTES['D4'], TEMPO * 354 // SUBDIV),
    (NOTES['C4'], TEMPO * 134 // SUBDIV),
    (NOTES['A#3'], TEMPO * 245 // SUBDIV),
    (NOTES['SILENCE'], TEMPO * 56 // SUBDIV),
    (NOTES['C4'], TEMPO * 534 // SUBDIV),
    (NOTES['G3'], TEMPO * 240 // SUBDIV),
    (NOTES['A#3'], TEMPO * 1200 // SUBDIV),
    (NOTES['G1'], TEMPO * 811 // SUBDIV),
    (NOTES['F1'], TEMPO * 1200 // SUBDIV),
    (NOTES['G3'], TEMPO * 480 // SUBDIV),
    (NOTES['A3'], TEMPO * 960 // SUBDIV),
    (NOTES['F2'], TEMPO * 960 // SUBDIV),
    (NOTES['D#2'], TEMPO * 1200 // SUBDIV),
    (NOTES['SILENCE'], TEMPO * 184 // SUBDIV),
    (NOTES['G3'], TEMPO * 960 // SUBDIV),
    (NOTES['A#3'], TEMPO * 267 // SUBDIV),
    (NOTES['C4'], TEMPO * 379 // SUBDIV),
    (NOTES['C4'], TEMPO * 1417 // SUBDIV),
    (NOTES['A#3'], TEMPO * 301 // SUBDIV),
    (NOTES['SILENCE'], TEMPO * 72 // SUBDIV),
    (NOTES['G3'], TEMPO * 480 // SUBDIV),
    (NOTES['G3'], TEMPO * 1440 // SUBDIV),
    (NOTES['SILENCE'], TEMPO * 56 // SUBDIV),
    (NOTES['D#2'], TEMPO * 960 // SUBDIV),
    (NOTES['C2'], TEMPO * 960 // SUBDIV),
    (NOTES['D2'], TEMPO * 1200 // SUBDIV),
    (NOTES['SILENCE'], TEMPO // SUBDIV),
    (NOTES['G3'], TEMPO * 323 // SUBDIV),
    (NOTES['A#3'], TEMPO * 245 // SUBDIV),
    (NOTES['C4'], TEMPO * 334 // SUBDIV),
    (NOTES['C#4'], TEMPO * 189 // SUBDIV),
    (NOTES['SILENCE'], TEMPO // SUBDIV),
    (NOTES['D4'], TEMPO * 412 // SUBDIV),
    (NOTES['G4'], TEMPO * 235 // SUBDIV),
    (NOTES['SILENCE'], TEMPO * 23 // SUBDIV),
    (NOTES['C#4'], TEMPO * 486 // SUBDIV),
    (NOTES['A#3'], TEMPO * 216 // SUBDIV),
    (NOTES['C4'], TEMPO * 334 // SUBDIV),
    (NOTES['SILENCE'], TEMPO * 45 // SUBDIV),
    (NOTES['G3'], TEMPO * 178 // SUBDIV),
    (NOTES['SILENCE'], TEMPO * 11 // SUBDIV),
    (NOTES['A#3'], TEMPO * 1398 // SUBDIV),
    (NOTES['G1'], TEMPO * 350 // SUBDIV),
    (NOTES['G1'], TEMPO * 240 // SUBDIV),
    (NOTES['G1'], TEMPO * 240 // SUBDIV),
    (NOTES['F1'], TEMPO * 1440 // SUBDIV),
    (NOTES['SILENCE'], TEMPO * 314 // SUBDIV),
    (NOTES['A#3'], TEMPO * 323 // SUBDIV),
    (NOTES['SILENCE'], TEMPO * 67 // SUBDIV),
    (NOTES['C4'], TEMPO * 279 // SUBDIV),
    (NOTES['SILENCE'], TEMPO * 22 // SUBDIV),
    (NOTES['A#3'], TEMPO * 279 // SUBDIV),
    (NOTES['SILENCE'], TEMPO * 10 // SUBDIV),
    (NOTES['A3'], TEMPO * 1106 // SUBDIV),
    (NOTES['SILENCE'], TEMPO * 267 // SUBDIV),
    (NOTES['A3'], TEMPO * 256 // SUBDIV),
    (NOTES['SILENCE'], TEMPO * 33 // SUBDIV),
    (NOTES['G3'], TEMPO * 223 // SUBDIV),
    (NOTES['SILENCE'], TEMPO * 101 // SUBDIV),
    (NOTES['D#3'], TEMPO * 800 // SUBDIV),
    (NOTES['C3'], TEMPO * 240 // SUBDIV),
    (NOTES['SILENCE'], TEMPO * 110 // SUBDIV),
    (NOTES['A3'], TEMPO * 234 // SUBDIV),
    (NOTES['SILENCE'], TEMPO * 22 // SUBDIV),
    (NOTES['G3'], TEMPO * 594 // SUBDIV),
    (NOTES['D#3'], TEMPO * 1440 // SUBDIV),
    (NOTES['C3'], TEMPO * 960 // SUBDIV),
    (NOTES['D3'], TEMPO * 960 // SUBDIV),
    (NOTES['D2'], TEMPO * 1680 // SUBDIV),
]