#!/usr/bin/env python3
import sys
import glob
import os
from PIL import Image
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt

# --- UTILS ---

def image_to_hlsb_bytes(img, invert=False):
    """
    Convert a PIL Image to MONO_HLSB bytearray (SSD1306 format).
    """
    img = img.convert('1') # Ensure 1-bit
    width, height = img.size
    
    buffer = bytearray()
    
    # HLSB: Horizontal mapping
    for y in range(height):
        for x in range(0, width, 8):
            byte_val = 0
            for bit in range(8):
                if x + bit < width:
                    pixel = img.getpixel((x + bit, y))
                    
                    is_on = pixel > 0 # White pixel
                    if invert:
                        is_on = not is_on
                        
                    if is_on: 
                        byte_val |= (1 << (7 - bit))
            buffer.append(byte_val)
            
    return buffer

def append_to_assets(var_name, data, source_info, console):
    """Appends or updates the generated bytearray in assets.py"""
    byte_str = "".join([f"\\x{b:02x}" for b in data])
    
    # Read existing content
    with open("assets.py", "r") as f:
        content = f.read()
        
    # Check if variable already exists
    if f"{var_name} =" in content:
        console.print(f"\n[yellow]Warning: Variable '{var_name}' already exists in assets.py[/yellow]")
        overwrite = Prompt.ask("Do you want to overwrite it?", choices=["y", "n"], default="y")
        
        if overwrite.lower() == 'n':
            console.print("[dim]Operation cancelled.[/dim]")
            return False
            
        # Remove old definition (simple heuristic: remove lines starting with var_name until empty line)
        # This is a bit risky with regex, let's try a safer approach:
        # We will append the NEW definition at the end, but verify if we can clean the old one.
        # For now, let's just append and warn the user that it might be duplicated if not careful,
        # OR we can try to replace it.
        
        # Better approach: Read lines, filter out the old definition block, then append new one.
        lines = content.splitlines()
        new_lines = []
        skip = False
        
        for line in lines:
            if line.startswith(f"{var_name} ="):
                skip = True
            elif skip and line.strip() == "":
                skip = False # End of block (assuming empty line after definition)
                continue # Skip the empty line too to avoid double gaps
            elif skip and (line.startswith("#") or "=" in line):
                # If we find another definition or comment while skipping, stop skipping
                # This is a safety fallback in case there was no empty line
                if "=" in line: 
                    skip = False
                    new_lines.append(line)
                continue
            
            if not skip:
                new_lines.append(line)
                
        content = "\n".join(new_lines)
        
        # Clean up multiple empty lines at the end
        content = content.rstrip() + "\n"
        
        with open("assets.py", "w") as f:
            f.write(content)
            
        console.print(f"[dim]Removed old definition of '{var_name}'.[/dim]")

    # Append new definition
    lines = []
    lines.append(f"# Source: {source_info}")
    lines.append(f"{var_name} = bytearray(b'{byte_str}')")
    lines.append("")
    
    with open("assets.py", "a") as f:
        f.write("\n" + "\n".join(lines))
        
    return True

# --- MAIN LOGIC ---

def main():
    console = Console()
    
    # 1. Search for PNG files
    # Recursive search in assets/
    png_files = glob.glob("assets/**/*.png", recursive=True)
    
    if not png_files:
        console.print("[bold red]Error:[/bold red] No .png files found in 'assets/' folder.")
        sys.exit(1)
        
    # 2. Show Menu
    console.print(Panel("Select an image to convert to Python bytearray:", title="[bold cyan]Image Converter[/bold cyan]"))
    
    for i, path in enumerate(png_files):
        console.print(f"  [yellow]{i+1}[/yellow]. {path}")
        
    choice = Prompt.ask("\n[bold]Choose file[/bold]", choices=[str(i+1) for i in range(len(png_files))])
    selected_file = png_files[int(choice) - 1]
    
    # 3. Ask for Variable Name
    default_var = os.path.basename(selected_file).replace('.png', '').upper()
    var_name = Prompt.ask("[bold]Variable Name[/bold]", default=default_var)
    
    # 4. Invert option
    invert = Prompt.ask("[bold]Invert colors? (Black->White)[/bold]", choices=["y", "n"], default="n")
    do_invert = (invert.lower() == 'y')
    
    # 5. Process
    console.print(f"\n[dim]Processing {selected_file}...[/dim]")
    try:
        img = Image.open(selected_file)
        width, height = img.size
        console.print(f"  Size: {width}x{height}")
        
        data = image_to_hlsb_bytes(img, do_invert)
        
        # 6. Write to assets.py
        info_str = f"{selected_file} ({width}x{height})"
        if do_invert:
            info_str += " [INVERTED]"
            
        if append_to_assets(var_name, data, info_str, console):
            console.print(f"[bold green]✓ Successfully updated '{var_name}' in assets.py[/bold green]")
        
    except Exception as e:
        console.print(f"[bold red]Error:[/bold red] {e}")

if __name__ == "__main__":
    main()
